apiVersion: v1
kind: Secret
metadata:
  name: csi-s3-secret
stringData:
  accessKeyID: 
  secretAccessKey: 
  # For AWS set it to "https://s3.<region>.amazonaws.com"
  endpoint: https://s3.us-east-2.amazonaws.com
  # If not on S3, set it to ""
  region: us-east-2